### ISSUE TITLE
Enable `compilerOptions.rewriteRelativeImportExtensions` in the `tsconfig.json` file

### ISSUE THREAD

**Issue by dustin-ruetz** [dustin-ruetz/web-devdeps#76]
## Prerequisites

- [x] The [`rewriteRelativeImportExtensions`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7/#path-rewriting-for-relative-paths) option should be documented on the [TSConfig Reference](https://www.typescriptlang.org/tsconfig/#rewriteRelativeImportExtensions) page.

## Tasks

- In the `tsconfig.json` file:
  - [x] ~~Set `"allowImportingTsExtensions": true`~~
    - Note: [`allowImportingTsExtensions`](https://www.typescriptlang.org/tsconfig/#allowImportingTsExtensions) is intended for something else and is therefore not needed.
  - [x] Set `"rewriteRelativeImportExtensions": true`
- [x] Add assertion for the above options in the `__tests__/tsconfigJSON.test.ts` file.
- [x] Update all import statements from `*.js` to `*.ts`.
- [x] Update the `jest.mock` calls from `*.js` to `*.ts`.
- [x] Verify that all of the most useful NPM scripts listed in the `README.md` file under ["Local Development"](https://github.com/dustin-ruetz/web-devdeps#local-development) work as expected.
